[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs_20", "nginx", "libmysqlclient"]

[phases.install]
cmds = [
  "mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx",
  "composer install --ignore-platform-reqs",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

# REMOVE or comment out the release phase
# [phases.release]
# cmds = ["php artisan migrate --force"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"